[project]
name = "demo-roller485"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "kaitaistruct>=0.11",
    "pyserial>=3.5",
]

[project.scripts]
roller485 = "roller485.cli:main"
